# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99af0f07ceb093640821d161d8f33a7467b6c6234e2cd28c0e4598bc843f13b294541f4250ba1a730143ba0731e185ec362c6ebdeedd5512af4e032af4a079aa

test:
  secret_key_base: aa102baa4ce312ef8a15ae59c1883819990136f91f7d56901f7417af997d4decb254e9588ccc2a4908b1b00631f93590c548d92021b71f8384e64ca32d5ef842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
